version: '3.4'
services:

  duckling-server:
    image: rasa/duckling:latest
    ports:
    - 5063:5063
    networks:
    - all

  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5063:5063'
    public: true
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
    - '5058:5058'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
